import { Creator, Metric, ChartDataPoint } from './types';

export const CREATORS: Creator[] = [
  {
    id: 'creator-1',
    name: 'Elena Rostova',
    role: 'Cinematic Documentarian',
    campaigns: 24,
    reach: '4.2M',
    followersCount: 4.2,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&h=600&q=80&sat=-100',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-cinematic-foggy-pine-forest-4881-large.mp4',
    bio: 'Elena explores the intersections of architecture and natural silence. Her slow-pan cinematic narratives underwrite major spatial and industrial designs.',
    country: 'Switzerland',
    countryCode: 'CH',
    platform: '35mm Film',
    csat: '98.4%',
    specialty: '35mm Anamorphic',
    badge: 'Tier 01 // Cannes Gold',
  },
  {
    id: 'creator-2',
    name: 'Julian Vance',
    role: 'Industrial Designer & Essayist',
    campaigns: 18,
    reach: '2.8M',
    followersCount: 2.8,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&h=600&q=80&sat=-100',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-thick-fog-over-mountains-and-forests-42457-large.mp4',
    bio: 'Julian creates tactile, close-up documentation on the lifecycle of mechanical craftsmanship and minimal product architectures.',
    country: 'United States',
    countryCode: 'US',
    platform: 'Editorial Essay',
    csat: '96.2%',
    specialty: 'Minimalist Industrial',
    badge: 'Verified Specialist',
  },
  {
    id: 'creator-3',
    name: 'Sarah Chen',
    role: 'Computational Artist',
    campaigns: 31,
    reach: '5.6M',
    followersCount: 5.6,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&h=600&q=80&sat=-100',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-waves-breaking-on-the-shore-from-above-4122-large.mp4',
    bio: 'Sarah generates large-scale algorithmic visualizations tracking global weather fluctuations and resource scarcity metrics.',
    country: 'Japan',
    countryCode: 'JP',
    platform: 'Generative AI',
    csat: '99.1%',
    specialty: 'Algorithmic Data Art',
    badge: 'Ars Electronica Laureate',
  },
  {
    id: 'creator-4',
    name: 'Marcus Thorne',
    role: 'Investigative Tech Journalist',
    campaigns: 15,
    reach: '1.9M',
    followersCount: 1.9,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&h=600&q=80&sat=-100',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-dramatic-clouds-at-sunset-1002-large.mp4',
    bio: 'Marcus writes deep-dive research dossiers on technical centralization, hardware supply chains, and digital privacy networks.',
    country: 'United Kingdom',
    countryCode: 'UK',
    platform: 'Editorial Essay',
    csat: '94.8%',
    specialty: 'Privacy & Hardware Audits',
    badge: 'Pulitzer Nominee',
  },
  {
    id: 'creator-5',
    name: 'Kaelen Miller',
    role: 'Sonic Architect & Sound Designer',
    campaigns: 12,
    reach: '1.2M',
    followersCount: 1.2,
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&h=600&q=80&sat=-100',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-misty-mountains-under-a-gloomy-sky-42442-large.mp4',
    bio: 'Kaelen researches spatial acoustics and sound synthesis, curating immersive audio landscapes for high-end exhibition spaces.',
    country: 'Germany',
    countryCode: 'DE',
    platform: 'Spatial Audio',
    csat: '97.5%',
    specialty: 'Dolby Atmos Soundscapes',
    badge: 'Spatial Audio Fellow',
  },
  {
    id: 'creator-6',
    name: 'Anya Varma',
    role: 'Experimental Photojournalist',
    campaigns: 22,
    reach: '3.1M',
    followersCount: 3.1,
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=600&h=600&q=80&sat=-100',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-light-shining-through-foggy-trees-41006-large.mp4',
    bio: 'Anya captures raw, high-contrast monochrome social essays, documenting artisanal traditions across sub-polar communities.',
    country: 'Switzerland',
    countryCode: 'CH',
    platform: 'Documentary',
    csat: '95.6%',
    specialty: 'Monochrome Sub-Polar Essays',
    badge: 'World Press Photo Winner',
  },
  {
    id: 'creator-7',
    name: 'Kenzo Takahashi',
    role: 'Spatial Systems Architect',
    campaigns: 19,
    reach: '4.8M',
    followersCount: 4.8,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&h=600&q=80&sat=-100',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-thick-fog-over-mountains-and-forests-42457-large.mp4',
    bio: 'Kenzo builds spatial interface prototypes and mixed reality architectural tours for luxury real estate and aerospace houses.',
    country: 'Japan',
    countryCode: 'JP',
    platform: 'Spatial Audio',
    csat: '98.9%',
    specialty: 'Mixed Reality Spatial Tours',
    badge: 'Spatial Innovation Award',
  },
  {
    id: 'creator-8',
    name: 'Claire Dupont',
    role: 'Haute Horology Historian',
    campaigns: 27,
    reach: '3.5M',
    followersCount: 3.5,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&h=600&q=80&sat=-100',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-cinematic-foggy-pine-forest-4881-large.mp4',
    bio: 'Claire authors exhaustive archives on watchmaker lineages, movement complications, and precious metal metallurgy.',
    country: 'Switzerland',
    countryCode: 'CH',
    platform: 'Editorial Essay',
    csat: '99.4%',
    specialty: 'Horological Metallurgy Archives',
    badge: 'GPHG Jury Fellow',
  }
];

export const METRICS: Metric[] = [
  {
    id: 'metric-reach',
    label: 'Total Network Reach',
    value: 18800000,
    format: 'number',
    trend: 'up',
    change: '+14.2%'
  },
  {
    id: 'metric-sponsorships',
    label: 'Co-Production Assets',
    value: 142,
    format: 'number',
    trend: 'up',
    change: '+8.3%'
  },
  {
    id: 'metric-revenue',
    label: 'Managed Capital Underwrite',
    value: 3850000,
    format: 'currency',
    trend: 'up',
    change: '+22.1%'
  },
  {
    id: 'metric-engagement',
    label: 'Audience Read Completion',
    value: 84.6,
    format: 'percent',
    trend: 'up',
    change: '+4.1%'
  }
];

export const CHART_DATA: ChartDataPoint[] = [
  { label: 'Q1', value: 12.4, secondary: 8.2 },
  { label: 'Q2', value: 14.8, secondary: 9.5 },
  { label: 'Q3', value: 16.2, secondary: 11.1 },
  { label: 'Q4', value: 18.8, secondary: 12.8 }
];

export const DEMOGRAPHICS = [
  { label: 'Enterprise / B2B', percentage: 42, color: '#9C8465' },
  { label: 'Creative Tech', percentage: 28, color: '#52525B' },
  { label: 'Luxury & Lifestyle', percentage: 20, color: '#27272A' },
  { label: 'Research Institutions', percentage: 10, color: '#18181B' }
];
